

try:
  n1 = int(input('Digite um valor: '))
  n2 = int(input('Digite outro valor: '))


except:
  raise Exception('Uma excess√£o ocorreu')
  
else:
    print('Curiosamente, funcionou')

finally:
    print("Volte quando puder!")

